package com.alibaba.android.arouter.routes

import android.util.Log
import com.alibaba.android.arouter.facade.template.IRouteGroup
import com.alibaba.android.arouter.facade.template.IRouteRoot
import java.lang.Class
import kotlin.String
import kotlin.Unit
import kotlin.collections.MutableMap

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER.
 * 添加测试类 快速观察 AGP 插桩是否成功
 */
public class `ARouter$$Root$$fuck` : IRouteRoot {
    public override fun loadInto(routes: MutableMap<String, Class<out IRouteGroup>>?): Unit {
        if (routes == null) {
            return
        }
        Log.d("AGPBUGFIX", "fuck you ${System.currentTimeMillis()}")
    }
}
